[package]
name = "yad_core"
version = "1.1.0"
edition = "2024"
authors = ["KingBCats <johan@ezezzz.xyz>"]
description = "YAD is a lightweight binary file format designed for efficient data storage."
repository = "https://github.com/KingsBeCattz/yad"
readme = "readme.md"
keywords = ["yad", "nosql", "encode", "decode", "file_format"]
categories = ["encoding","data-structures"]
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/yad_core"

[dependencies]
float16 = "0.1.3"
float8 = "0.4.2"

[lib]
name = "yad_core"
crate-type = ["cdylib", "rlib"]

[[example]]
name = "example"
path = "examples/main.rs"

[package.metadata.docs.rs]
rustdoc-args = ["--generate-link-to-definition"]
